create table
  public.films (
    id bigint generated by default as identity not null,
    title text null,
    poster_path text null,
    created_at timestamp with time zone null default now(),
    constraint films_pkey primary key (id),
    constraint films_id_key unique (id)
  ) tablespace pg_default;